object Main {

  def main(args: Array[String]): Unit = {
    for(a <- args){
      a match {
        case "ConfrontoNumeroTweetsSandyJoplin"=>MultipleTypesQueries.confrontoTweets()
        case "StatisticheAttinenzaTweetSandy"=>MultipleTypesQueries.sandyStatistics()
        case  "StatisticheAttinenzaTweetJoplin"=>MultipleTypesQueries.joplinStatistics()
        case  "StatisticheTipoInformazioneTweetSandy"=>InfoTypesQueries.sandyStatistics()
        case  "StatisticheTipoInformazioneTweetJoplin"=>InfoTypesQueries.joplinStatistics()
        case  "ConfrontoTipoInformazioneTweetSandyJoplin"=>InfoTypesQueries.confronto()
        case  "StatisticheTipoAvvertimentoTweetSandy"=>TypeAdviceQueries.sandyStatistics()
        case  "StatisticheTipoAvvertimentoTweetJoplin"=>TypeAdviceQueries.joplinStatistics()
        case  "ConfrontoTipoAvvertimentoTweetSandyJoplin"=>TypeAdviceQueries.confronto()
        case  "TweetAllarmeSandy"=>TypeAdviceQueries.warningTweetsSandy()
        case  "TweetAllarmeJoplin"=>TypeAdviceQueries.warningTweetsJoplin()
        case  "TweetRifugioSandy"=>TypeAdviceQueries.shelterTweetsSandy()
        case  "TweetRifugioJoplin"=>TypeAdviceQueries.shelterTweetsJoplin()
        case  "TweetAvvistamentoSandy"=>TypeAdviceQueries.sightingTweetsSandy()
        case  "TweetAvvistamentoJoplin"=>TypeAdviceQueries.sightingTweetsJoplin()
        case  "TweetAltriAvvertimentiSandy"=>TypeAdviceQueries.otherTweetsSandy()
        case  "TweetAltriAvvertimentiJoplin"=>TypeAdviceQueries.otherTweetsJoplin()
        case  "TweetUditaSirenaJoplin" => TypeAdviceQueries.sirenTweetsJoplin()
        case  "StatisticheTipoDiDannoTweetSandy" => TypeDamageQueries.sandyStatistics()
        case  "StatisticheTipoDiDannoTweetJoplin" => TypeDamageQueries.joplinStatistics()
        case  "ConfrontoTipoDiDannoSandyJoplin" => TypeDamageQueries.confronto()
        case  "TweetPersoneCoinvolteSandy" => TypeDamageQueries.sandypeopleTweets()
        case  "TweetPersoneCoinvolteJoplin" => TypeDamageQueries.joplinpeopleTweets()
        case  "TweetInfrastruttureCoinvolteSandy" => TypeDamageQueries.sandyinfrastructureTweets()
        case  "TweetInfrastruttureCoinvolteJoplin" => TypeDamageQueries.joplininfrastructureTweets()
        case  "TweetDannoNonSpecificoSandy" => TypeDamageQueries.sandynotSpecifiedTweets()
        case  "TweetDannoNonSpecificoJoplin" => TypeDamageQueries.joplinnotSpecifiedTweets()
        case  "StatisticheTipoMediaSandy" => TypeMediaQueries.sandystatistics()
        case  "StatisticheTipoMediaJoplin" => TypeMediaQueries.joplinStatistics()
        case  "ConfrontoTipoMediaSandyJoplin" => TypeMediaQueries.confronto()
        case  "TweetPhotoSandy" => TypeMediaQueries.sandyphotoTweets()
        case  "TweetPhotoJoplin" => TypeMediaQueries.joplinphotoTweets()
        case  "TweetVideoSandy" => TypeMediaQueries.sandyvideoTweets()
        case  "TweetVideoJoplin" => TypeMediaQueries.joplinvideoTweets()
        case  "TweetTvSandy" => TypeMediaQueries.sandytvTweets()
        case  "TweetTvJoplin" => TypeMediaQueries.joplintvTweets()
        case  "TweetWebSandy" => TypeMediaQueries.sandywebTweets()
        case  "TweetWebJoplin" => TypeMediaQueries.joplinwebTweets()
        case  "TweetAltriMediaSandy" => TypeMediaQueries.sandyotherTweets()
        case  "TweetAltriMediaJoplin" => TypeMediaQueries.joplinotherTweets()
        case  "StatisticheTestimoniSandy" => eyeOnEventQueries.statistics()
        case  "TweetUtentiTestimoniSandy" => eyeOnEventQueries.eyeTweets()
        case  "UtentiTestimoniSandy" => eyeOnEventQueries.userTweets()
        case  "StatisticheDonazioniJoplin" => JoplinTypeDonationQueries.joplinStatistics()
        case  "TweetDonazioneCiboJoplin" => JoplinTypeDonationQueries.joplinDonationFoodTweets()
        case  "TweetDonazioneSangueJoplin" => JoplinTypeDonationQueries.joplinDonationBloodTweets()
        case  "TweetDonazioneAttrezzaturaJoplin" => JoplinTypeDonationQueries.joplinDonationEquipmentTweets()
        case  "TweetDonazioneDenaroJoplin" => JoplinTypeDonationQueries.joplinDonationMoneyTweets()
        case  "TweetDonazioneScontoJoplin" => JoplinTypeDonationQueries.joplinDonationDiscountTweets()
        case  "TweetDonazioneVolontariJoplin" => JoplinTypeDonationQueries.joplinDonationVolunteersTweets()
        case  "TweetAltreDonazioniJoplin" => JoplinTypeDonationQueries.joplinDonationOtherTweets()
        case  "TweetDonazioneRifugioJoplin" => JoplinTypeDonationQueries.joplinDonationShelterTweets()
        case  "StatisticheIndicazioniTweetSandy" => IstructionQueries.statistics()
      }
    }
  }

}
